### ISSUE TITLE
업데이트 한가지 건의해봅니다

### ISSUE THREAD

**Issue by myoungho-jung** [owjs3901/DeathPenalty#1]
죽을시 패널티를 자신이 착용한 갑옷중 랜덤으로 한가지만 드랍되게 했으면 좋겠습니다

여기서 더 나아가 몬스터한테 죽을때 패널티와 사람한테 죽을때 패널티를 다르게 설정할 수 있으면 좋을 것 같아요

**Comment by owjs3901** [comment]
좋은 의견 감사합니다.
반영해보도록 하겠습니다.

**Comment by owjs3901** [comment]
업데이트 되었습니다.
감사합니다
